---

  # - name: Provision virtual machine example
  #   azure:
  #     name: my-virtual-machine
  #     location: East US
  #     user: azadmin
  #     password: azaviatrix@123
  #     os_type: linux
  #     wait: True
  #     state: present
  #     subscription_id: c0e9a5e9-b9e8-478d-8369-c8879c7e5a64
  #     management_cert_path: /home/ramesh/.azure/credentials
  #     storage_account: azaviatrixuseastdiag510
  #     image:
  #       offer: Linux
  #       publisher: Canonical
  #       version: 16.04
  #   delegate_to: localhost
  #   register: vm_obj
  
  - name: launch
    azure_rm_virtualmachine:
      resource_group: AZ-aviatrix-us-east
      name: testvm10
      subscription_id: c0e9a5e9-b9e8-478d-8369-c8879c7e5a64
      storage_account: azaviatrixuseastdiag510
      # management_cert_path: /home/ramesh/.azure/credentials
      admin_username: azadmin
      admin_password: aviatrix@123
      ad_user: opcito.aviatrix@gmail.com
      password: Aviatrix123#
      image:
        offer: Linux
        publisher: Canonical
        version: 16.04
    register: vm_obj
  
  # - name: Add region name in hosts
  #   local_action: lineinfile 
  #                 dest="./hosts" 
  #                 regexp='(^\s+kernel(\s+(?!audit=1)[\w=/\-\.]+)*)\s*$'
  #                 line=[{{ dev_env.region }}]

  # - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  #   local_action: lineinfile 
  #                 dest="./hosts" 
  #                 regexp='(^\s+kernel(\s+(?!audit=1)[\w=/\-\.]+)*)\s*$'
  #                 line={{ item.public_ip }}
  #   with_items: "{{ ec2_obj.instances }}"


  # - name: Wait for SSH to come up
  #   local_action: wait_for 
  #                 host={{ item.public_ip }} 
  #                 port=22 
  #                 state=started
  #   with_items: "{{ ec2_obj.instances }}"

  # - name: Add tag to Instance(s)
  #   local_action: ec2_tag 
  #                 resource={{ item.id }} 
  #                 region={{ dev_env.region }} 
  #                 state=present
  #   with_items: "{{ ec2_obj.instances }}"
  #   args:
  #     tags:
  #       Name: aviatrix-agent-do-not-stop
