- name: install jdk8
  shell: 'add-apt-repository -y ppa:webupd8team/java && apt-get update && apt-get -y install oracle-java8-installer'

- name: Set gpg key of elastic search
  shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

- name: set yhe debian packages of elasticsearch
  shell: 'echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list'

- name: install elasticsearch
  shell: 'apt-get update && apt-get -y install elasticsearch'

- copy: copy elasticsearch configuration
  src: elasticsearch.yml
  dest: /etc/elasticsearch/elasticsearch.yml

- name: Start the elasticsearch service
  shell: 'service elasticsearch restart'
